### PR TITLE
Ignore vendor

### PR DESCRIPTION
**Pull request by knowler**

### CODE REVIEW

**Comment by MWDelaney** [comment]
Won't this break the autoloading of the `Init` class?

**Comment by knowler** [comment]
I figure that people would be installing this via:

```bash
composer require roots/roots-branding
```

**Comment by MWDelaney** [comment]
oh, yeah, probably.

**Comment by austinpray** [comment]
Just fyi not here in this project but elsewhere: this should almost universally be `/vendor`.

This rule would clobber `app/scripts/vendor/lodash.custom.js` for instance

**Pull request merged**
